# Generated by Django 5.1.4 on 2025-01-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_player_accurate_position_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('player', 'Player')], default='player', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='batting_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='home_runs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rbis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='stolen_bases',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
